### PR TITLE
course search tweaks

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

part of #2294 

#### What's this PR do?

this does a series of tweaks to the course search page:

- remove extra dollar sign from course price (only on the card, not in the drawer)
- values in the card description for platform, topic, etc should be links to a search for that value (e.g. clicking the 'Math' subject on a course should take you to a search for the 'Math' subject')
- only the favorite button in the bottom row of the card should have a 'link' cursor
- cards all over the site should have a hover state, where a box-shadow shows up (see designs)
- course home page search 'magnifying glass' icon should redirect to search with the text the user has entered (currently this behavior happens when you hit the enter key but not when you click the little icon)
- change home page link text from "View All" to "Explore"

#### How should this be manually tested?

make sure that the above tweaks a good on mobile, desktop

#### Screenshots (if appropriate)
topilinkffff
topilink
tweaks1fffjfjffff
tweaks1fffjfj
tweaks1

### CODE REVIEW

**Comment by rhysyngsun** [comment]
@aliceriot @pdpinch @Ferdi a few questions about what we were looking for here because it's a bit ambiguous from the issue:

- Should topics listed in the drawer also link to a search for those topics? We only list 2-3 at most in the card whereas the drawer lists them all
- Should availability be linked to a search also?
- Should the price be linked to a search? This one might be a bit odd because a course priced at $700 would link to a search for "Paid"

**Comment by rhysyngsun** [comment]
@aliceriot I'm seeing the cards on `/courses/` still getting the hand cursor for the entire card

**Comment by aliceriot** [comment]
@rhysyngsun thanks for pointing that out on the homepage, hadn't noticed it there. I think it should be overwritten now. I also fixed the platform -> offeredBy thing

**Comment by rhysyngsun** [comment]
Those two changes look good

**Comment by Ferdi** [comment]
> Should topics listed in the drawer also link to a search for those topics? We only list 2-3 at most in the card whereas the drawer lists them all

Yes , it's ok if it's  in a separate PR

Availability and price, probably not for now

**Pull request merged**
