### PR TITLE
CSAIL course import

### LINKED ISSUE #2738: Add CSAIL course offerings
https://cap.csail.mit.edu/ -> offered by "CSAIL"

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested
- [x] Settings
  - [x] New settings are documented and present in `app.json`
  - [x] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Closes #2738 

#### What's this PR do?
Imports CSAIL courses (all 3 of them 😉)
 
#### How should this be manually tested?
- Set `CSAIL_BASE_URL=https://cap.csail.mit.edu/` in your .env file
- Run `manage.py backpopulate_csail_data`
- Check the course search page, there should be 3 CSAIL courses
- Topic is hardcoded to "Computer Science" after discussing w/Peter.

#### Screenshots (if appropriate)
Screen Shot 2020-04-09 at 11 25 35 AM

Screen Shot 2020-04-09 at 11 25 48 AM

### CODE REVIEW

**Comment by mbertrand** [comment]
@pdpinch @Ferdi @abdulkdawson screenshots for CSAIL courses are in the description

**Comment by aliceriot** [comment]
I tried this out and everything works well - I'm just wondering if the overall approach makes sense. If they change how they format these pages our scraper could stop working. Is it worth it to implement something like this just for three courses? I suppose the advantage is we can be sure we're up to date, but I'm wondering if this strategy will end up being fragile in the long run. Maybe I'm worrying over-much though.

**Comment by mbertrand** [comment]
The scraper will stop working if they change their HTML format, but unfortunately they don't have any standard API to get course info from, so using BeautifulSoup to extract the data from the current HTML formatting is the only option right now.  Supposedly more courses will be added in the future.

**Comment by aliceriot** [comment]
ok, I mean I think we can go forward with this, and it will make sense to have an automated thing for more courses. I was just thinking that if there were only three it may be simpler to just input these things manually. Just wanted to make sure I raised that, haha.

**Pull request merged**
