### PR TITLE
add a 404 message to the channel page

### LINKED ISSUE #393: User requesting a channel without permission raises a 403 error on moderator API
This doesn't affect user experience, but leads to an error in Sentry.

### LINKED ISSUE #408: Requesting a non-existant channel raises an error to Sentry instead of returning 404
I thought we had addressed this in #319/#293 but I saw the error below in Sentry:

Redirect: Redirect to /subreddits/search

https://sentry.io/mit-office-of-digital-learning/discussions/issues/421462250/

```
Redirect: Redirect to /subreddits/search
(15 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/generics.py", line 240, in get
    return self.list(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "channels/views.py", line 88, in get_queryset
    return api.list_moderators(channel_name)
  File "channels/api.py", line 756, in list_moderators
    return self.get_channel(channel_name).moderator(redditor=moderator_name)

Redirect: Redirect to /subreddits/search
```

The user experience needs work too, similar to #215. The user simply gets the message "Error loading page"

https://www.dropbox.com/s/0s85ay9u5y7ra7u/Screenshot%202017-12-20%2008.03.11.png?dl=0

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #408 
closes #393 

#### What's this PR do?

This adds a 404 page to the channel, which you should see if you try to visit a channel that doesn't exist. I also moved stuff around so we no longer raise an unhandled exception when the request comes back with a 404.

Additional, there was previously an issue where if you visited a post that doesn't exist and then tried to navigate to a channel, the 404 error from the post would prevent the channel data from showing itself. To fix this I just added an action to the post reducer to clear out the error state, which we can call on the channel page if we need to.

#### How should this be manually tested?

Go to something like `/channel/flflasdfajsdf` (well unless you have a channel called that :P). You should see a 404 message, like what we have now on the post page. Then if you visit another channel all should be well. Additionally, the error situation I described above (visiting a 'not found' post and then going to a channel page) should no longer raise any errors.

### CODE REVIEW

**Comment by noisecapella** [comment]
If I go to a channel name with one letter I still see an error page. I'm not sure what reddit's doing there. Can you investigate that?

**Comment by noisecapella** [comment]
It looks like the error page after navigating from a 404 post page to a channel page is fixed, but I still see it when I navigate from a 404 channel page to another channel page via sidebar

**Comment by noisecapella** [comment]
One more case: if I go to a 404 post page, then navigate to a channel page, then navigate to another post which does exist, I see a 404 post page for that page

**Comment by aliceriot** [comment]
with the one-letter thing, it seems (by doing some experimenting in the console) that Reddit returns a 400 from a one-letter subreddit, not sure why exactly

**Comment by aliceriot** [comment]
I get a 404 when I try https://www.reddit.com/r/f, so maybe it's something praw is doing? idk

**Comment by noisecapella** [comment]
@rhysyngsun do you know what the regex is that reddit uses to enforce channel names? How do we do it when the user creates a new channel?

**Comment by noisecapella** [comment]
Maybe we can just change the regex in `urls.py` to require at least two characters for the channel names for the API. That will automatically return a 404 if the regex doesn't match

**Comment by aliceriot** [comment]
I'm fine with that approach, it seems like reddit does not allow one-letter subreddit names (based on a quick check) so we should be ok doing that.

**Comment by aliceriot** [comment]
Ok I think issues should be addressed. For the navigation error I just made the PostPage clean up after itself more (it checks if it has an error and, if so, clears it on `ComponentWillUnmount`). I also added a thingy to clear the post error on the channel page, which should help with navigating between channels.

For the 404 issue, I tried changing the regex in urls.py, but I ran into an issue. Basically if django doesn't match a url it returns a 404, but it doesn't return JSON, which the frontend expects. Because of this, I ended up adding a little thingy to the channel detail view, which just checks for a one-letter channel name and returns a 404 if it finds one (so we don't hit reddit and blow things up, haha).

**Comment by aliceriot** [comment]
@noisecapella I think this should also address #393, so if you visit a channel that exists but you do not have permission for you should not have unhandled promise rejections

**Comment by noisecapella** [comment]
I'm still seeing #393:
screenshot from 2018-01-09 15-51-36

**Comment by noisecapella** [comment]
Everything else looks good

**Comment by aliceriot** [comment]
Ok I think I addressed that, I just made it so that we only kick off the channel moderators request if the get channel request comes back without an error

**Pull request merged**
