### PR TITLE
fix salutation

### PR DESCRIPTION
**Pull request by abeglova**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
closes https://github.com/mitodl/open-discussions/issues/3375

#### What's this PR do?
This pr stores the correct salutation in the full_name field for OCW course instructors

#### How should this be manually tested?
Run
```
from course_catalog.api import *

sync_ocw_courses(course_prefixes=["PROD/8/8.01/Fall_2016/8-01sc-classical-mechanics-fall-2016/"], blocklist=[], force_overwrite=True, upload_to_s3=False)
```

Go to \learn\search and find the "Classical Mechanics" course on OCW

Verify that the instructors field is
```
Prof. Deepto Chakrabarty, Dr. Peter Dourmashkin, Prof. Anna Frebel, Dr. Michelle Tomasik, Prof. Vladan Vuletic
```

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
Looks good and worked as expected, but then when I ran `backpopulate_edx_data` afterward I got this error:

```
celery_1   | [2021-04-30 15:35:01,949: ERROR/ForkPoolWorker-2227] Task course_catalog.tasks.get_mitx_data[d4209223-8b0c-4890-a076-fc0b99b22064] raised unexpected: MultipleObjectsReturned('get() returned more than one CourseInstructor -- it returned 2!')
celery_1   | Traceback (most recent call last):
celery_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
celery_1   |     R = retval = fun(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
celery_1   |     return self.run(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
celery_1   |     reraise(*exc_info)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
celery_1   |     raise value
celery_1   |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
celery_1   |     return f(*args, **kwargs)
celery_1   |   File "/src/course_catalog/tasks.py", line 34, in get_mitx_data
celery_1   |     pipelines.mitx_etl()
celery_1   |   File "/usr/local/lib/python3.7/site-packages/toolz/functoolz.py", line 488, in __call__
celery_1   |     ret = f(ret)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/toolz/functoolz.py", line 303, in __call__
celery_1   |     return self._partial(*args, **kwargs)
celery_1   |   File "/src/course_catalog/etl/loaders.py", line 271, in load_courses
celery_1   |     for course in courses_list
celery_1   |   File "/src/course_catalog/etl/loaders.py", line 271, in <listcomp>
celery_1   |     for course in courses_list
celery_1   |   File "/src/course_catalog/etl/loaders.py", line 233, in load_course
celery_1   |     load_run(course, course_run_data, config=config.runs)
celery_1   |   File "/src/course_catalog/etl/loaders.py", line 161, in load_run
celery_1   |     load_instructors(learning_resource_run, instructors_data)
celery_1   |   File "/src/course_catalog/etl/loaders.py", line 88, in load_instructors
celery_1   |     instructor, _ = CourseInstructor.objects.get_or_create(**instructor_data)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
celery_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
celery_1   |     return self.get(**kwargs), False
celery_1   |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 412, in get
celery_1   |     (self.model._meta.object_name, num)
celery_1   | course_catalog.models.CourseInstructor.MultipleObjectsReturned: get() returned more than one CourseInstructor -- it returned 2!
```

Got the same error again after deleting all instructors from the database and reimporting the ocw course followed by the backpopulate_edx command. I plan to try again on master but looks like I need to wait a bit now because I got a 'Too Many Requests' error on my last try.

**Comment by abeglova** [comment]
Thanks for catching that @mbertrand

**Comment by abeglova** [comment]
I pushed up a fix

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
