### PR TITLE
Channel design updates

### LINKED ISSUE #1327: Channel Header design updates
Zeplin: https://zpl.io/bWLwOyP
InVision: https://invis.io/9EN908ZQPAX#/324748827_Channel_Full_Update_10_Oct

### acceptance criteria 
- [x] Channel banner: update the height of the channel banner in the template to 200px
- [x] Channel banner: update the height to 200px in the Channel settings form
- [x] Channel banner: Standardize on **one** background color, with no gradient
- [x] Channel banner: Add a semitransparent gradient *above* the channel title, headline and banner to help make the text more legible (see Zeplin for details)
- [x] Left nav: adjust the spacing of items in the left nav, based on Zeplin. 
  - [x] close up the gap between the compose button & the "channels I moderate" header
- [x] Channel Nav: Change "Posts" tab on channel pages to "Home"
- [x] Channel Nav: add white tab area across width of page 
- [x] Channel Nav: restyle the channel tabs
- [x] Channel Nav: remove the "All" filter in the channel template (we have no plans as yet for filtering channels)
- ~~move the channel sort dropdown to the left (where the filter used to be)~~ (don't move it)
- [x] Channel Avatar: Standardize on one background, without gradient
- [x] Channel Avatar: update the font size of the initials

### related issues
- this affects the location of the channel search form
- there are similar changes to the home page, but I don't think they share components

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots 
  - [x] Mobile width screenshots 
  - [x] tag @ferdi or @pdpinch for review  
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #1327 

#### What's this PR do?
Implements channel design tweaks

#### How should this be manually tested?
Make sure the design matches and everything still works

#### Screenshots (if appropriate)
Channel:
screenshot_2018-10-12 spaaaaaaace mit open discussions 1
screenshot_2018-10-17 spaaaaaaace mit open learning

Frontpage:
screen shot 2018-10-18 at 11 10 26
screen shot 2018-10-18 at 11 10 23

@Ferdi @pdpinch

### CODE REVIEW

**Comment by noisecapella** [comment]
It looks like the Home tab should have the same font size as the sidebar channel links according to Zeplin, 18px

**Comment by noisecapella** [comment]
On the home page I'm seeing this:
screenshot from 2018-10-17 15-59-09

**Comment by noisecapella** [comment]
Otherwise everything looks great

**Comment by rhysyngsun** [comment]
@noisecapella I've removed the "Home" text

**Comment by pdpinch** [comment]
We have a new design for the home (see issue #1384). 

To manage the scope of this PR, I think the easiest thing to do would be to remove the IntraPageNav component from the home page:

https://github.com/mitodl/open-discussions/blob/30beb39d8b32659b7a5bc75eee5964f74d496628/static/js/containers/HomePage.js#L132-L136

**Comment by rhysyngsun** [comment]
@noisecapella I've updated the code and screenshots to remove the nav on the homepage as @pdpinch requested, could you give it a quick look?

**Comment by pdpinch** [comment]
So, there is a change to the mobile design that I forgot to add to this issue. We want to hide the channel avatar on mobile. 

See https://zpl.io/2vW869r

**Pull request merged**
