### PR TITLE
add a link to the settings

### LINKED ISSUE #545: Add a link to "Settings" in the sidenav
image

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #545 

#### What's this PR do?

it adds a link to the settings page to the navigation menu

#### How should this be manually tested?

Make sure it shows up, and takes you to the right place!

### CODE REVIEW

**Comment by aliceriot** [comment]
sorry - should have probably put a note here, but I think it's not clear exactly what we want, design-wise, for this yet, so this is almost certainly not the final code.

**Comment by aliceriot** [comment]
currently this looks like:

settingslink

settingslinkmob

**Comment by aliceriot** [comment]
^^ @roberthouse54

**Comment by roberthouse54** [comment]
Looks good @aliceriot thanks. I think the settings link is slightly indented an not totally aligned with the links above. Can you fix that?

image

**Comment by aliceriot** [comment]
@rhysyngsun is this unblocked now?

**Comment by rhysyngsun** [comment]
@aliceriot yeah this can merge

**Pull request merged**
