### PR TITLE
fix mobile styling of dialog

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?

just noticed we have an issue with the dialog on mobile, see screenshots below. CSS only fix.

#### What's this PR do?

fixes an issue where the top of the dialog was getting cut off by our top bar on mobile (or on any short device really).

#### How should this be manually tested?

confirm the issue on master, then check this out and confirm it fixes it without doing anything too weird.

#### Screenshots (if appropriate)

before:

fixedthedialogfff

after:

fixedthedialog

### CODE REVIEW

**Comment by rhysyngsun** [comment]
@aliceriot those changes look good, but I think it's worth fixing the overflowing text on the list type options while we're in here

**Comment by aliceriot** [comment]
I left that off for now since we don't have a mobile design for that form yet, at least as far as I've seen

**Comment by abdulkdawson** [comment]
@aliceriot @pdpinch Here is the InVision link to the mobile design for the form. [https://projects.invisionapp.com/d/main#/console/18274223/396552777/preview](https://projects.invisionapp.com/d/main#/console/18274223/396552777/preview)

**Comment by aliceriot** [comment]
thanks for posting, I'll make an issue to implement that!

**Pull request merged**
