### PR TITLE
Make sure object_type is always merged in when retrieving entities from state

### LINKED ISSUE #2228: Clicking course card to display drawer only works once
### Steps to Reproduce

1. Navigate to /courses/
2 Click on a course card
3. The drawer loads
4. Click anywhere off the drawer to dismiss it. 
5. Click on the same course card again

### Expected Behavior

- Drawer should load again. 

### Actual Behavior

- Nothing happens
- No errors in the console 

### Screenshot or Screencast

https://embed.vidyard.com/share/idwpYJTGUwoFPBZwk6V1v5?

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #2228

#### What's this PR do?
Merges the object_type property with appropriate value into entities retrieved from state.

#### How should this be manually tested?
- Click a new course on the index page to bring up the drawer. Close it and repeat.  The drawer should open every time.
- Add some favorite courses and bootcamps, and click on them too in the Favorites carousel.

### CODE REVIEW

**Comment by aliceriot** [comment]
I wonder with this, should we go to the step of adding it in at the API level so that we're assured that the value is always set for the frontend?

**Comment by aliceriot** [comment]
the frontend code for a lot of these things could be simplified if we did that, for instance in the favorites API we currently get these `{ content_data, content_type }` records back - if the `content_type` were just set on the content itself then we could just have an `Array<LearningResource>` instead

**Comment by aliceriot** [comment]
I think the problem on the course carousel in particular is that when the drawer is opened we hit the relevant API, and then the response from the course API (the `courseRequest` mutation hits the relevant endpoint) overwrites the value already set in the store but it doesn't set the `object_type` value on it's response

**Comment by mbertrand** [comment]
@aliceriot I changed the approach and added `object_type` to the serializers instead.

**Pull request merged**
