### PR TITLE
dont start extra tasks for index updates

### PR DESCRIPTION
**Pull request by abeglova**
#### What are the relevant tickets?
closes https://github.com/mitodl/open-discussions/issues/4004

#### What's this PR do?
We had an issue where an ocw course was deleted and it took most of a day for the change to propagate to the search index.  Also for some of that time the course was already removed from the open database so it came up in /learn/search and /infinite/search but opened to a blank drawer. Not starting separate task for reindexing will improve the speed that things are indexed

#### How should this be manually tested?
Run some of the backpopulate_ tasks in course_catalog/management/ and verify that you don't see errors and the index is updating. 

Make a new post or comment in disscussions and verify that the new post is available in the  /search page

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
Works great locally, one concern though is that by calling the task immediately, any task decorator kwargs are ignored, for example lots of the index tasks use these:

```
PARTIAL_UPDATE_TASK_SETTINGS = dict(
    autoretry_for=(NotFoundError,),
    retry_kwargs={"max_retries": 5},
    default_retry_delay=2,
)

@app.task(**PARTIAL_UPDATE_TASK_SETTINGS)
def upsert_content_file(file_id):
    ....
```

Not sure how much of an impact this might have in production.  What do you think?

**Comment by abeglova** [comment]
So maybe we run it immediately, then start a task if something breaks?

**Comment by abeglova** [comment]
I think I thought of another potential issue - this change will prevent a task updating a batch of learning resources from completing if open search throws an error for a single item

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
