### PR TITLE
Numerous small tweaks to UI

### PR DESCRIPTION
**Pull request by roberthouse54**
#### What are the relevant tickets?
closes 244, closes 245, also 247, 238

#### What's this PR do?
This PR tweaks numerous css styles in Open Discussions, and makes other small UI changes:
- decreases the left margin for nested comments
- hides the user avatars on mobile in comments section.
- tightens up the vertical spacing between comments ansd slightly reduces the font size of comments
- Moves the "Submit Post" button up a bit.
- fixes a problem with the font in text areas on firefox
- Changes the title of the Home page to "Home" in both the card on the home page, and in the breadcrumbs (issues #244 and #245)
- Changes the site title in the Navbar to MIT | MicroMasters > Discussions. Discussions links to the home page in discussions. MicroMasters will link back to the MicroMasters dashboard (not in this PR. See: #253)
- Changes the image for upvoting and downvoting arrows.
- Other minor changes to link font color, margins in leftnav, etc.

#### How should this be manually tested?
Check that the changes do not break the layout anywhere.

### CODE REVIEW

**Comment by aliceriot** [comment]
it looks like the spacing around the breadcrumbs is slightly uneven on mobile:

uneven_spacing

it looks normal on desktop

**Comment by aliceriot** [comment]
other than that the layout and changes look good!

**Comment by aliceriot** [comment]
code looks good to, so just the question about the breadcrumb padding

**Comment by roberthouse54** [comment]
OK, I fixed the breadcrumb thing.

**Pull request merged**
