### PR TITLE
Move footer into sidebar

### LINKED ISSUE #986: New Footer
The new footer goes into the bottom of the left hand nav. 

See https://invis.io/9EN908ZQPAX#/311617691_Home_Not_Logged_Drawer

### acceptance criteria
- [ ] Omit About page link until we have an about page
- [ ] Community Guidelines link to /content_policy/ (should we change that URL?)
- [ ] TOS link

### related issues
- #985 replace MM TOS with MIT Open TOS

### PR DESCRIPTION
**Pull request by noisecapella**
**Rebased** on #1082 

#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #986 

#### What's this PR do?
Updates footer to match the mockup and moves it into the sidebar. The sidebar is changed to use flexbox and the footer is pushed to the bottom of the screen via flex-shrink

#### How should this be manually tested?
View the sidebar and verify that the footer sits at the bottom, looks good and the links work as before

### CODE REVIEW

**Comment by pdpinch** [comment]
@noisecapella can we get a screenshot, or a review app? -- whichever is easier

**Comment by aliceriot** [comment]
the spacing on the bottom two lines looks a little looser than what's in the mockup to my eyes:

new_footer

vs the mockup:

new_footermockup

**Comment by noisecapella** [comment]
@pdpinch 
screenshot from 2018-08-17 11-20-18

@aliceriot What do you think of the spacing now?

**Comment by aliceriot** [comment]
that looks good to me!

**Pull request merged**
