### PR TITLE
add cover image to course index page

### LINKED ISSUE #1800: Course index page
As a learner, I'd like to get an introduction to what online courses are offered by Open Learning. 

See https://zpl.io/VDqmDNJ

### acceptance criteria:
- [x] behind a feature flag (can be the same for the course search interface)
- [x] omit "recommended for you" for MVP 
- [x] the list of "featured" courses can be managed manually in the django admin
- [x] there should already be an API for "upcoming courses" a date-sorted list of courses with start dates in the future
- [x] there should already be an API for "new courses," the most recently created courses
- [x] banner for course index page

### out of scope
- "recommended for you" courses

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #1800 

#### What's this PR do?

this adds a cover image to the top of the course index page. for now it is just showing the fallback background color and gradient that we show on the channel page when the no channel cover image has been set.

#### How should this be manually tested?

To implement this I refactored the styling for the channel cover image into reusable components so we could share the implementation with the course index page. So check that the channel header looks good and is working correctly on all the pages where it is present (channel page, post page, channel settings, etc).

also check that it is display correctly on the course index page. nothing should be weird!

also the search box on the channel index page should work correctly. if you type in a query and hit enter it should redirect you over to the course search page, and show the results for the query you just typed in.

#### Screenshots (if appropriate)

fjfjfjfjfjfj

### CODE REVIEW

**Comment by aliceriot** [comment]
oh oops forgot about that picture!

**Comment by aliceriot** [comment]
for the placeholder text I just copied what was on the mockup (see here: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5c4efd5da6396e444e8bd39a)

for that issue with the text are you seeing it at a normal desktop screenwidth?

**Comment by mbertrand** [comment]
@aliceriot the text is cut off at all browser widths, I double-checked that browser zoom was 100%.  I need to zoom out to 67% before I can see all the text.  Chrome only, on FF and Safari it's fine.

**Comment by aliceriot** [comment]
huh that's weird, it looks fine on my machine, I checked on chrome and chromium. maybe it is a mac-specific thing?

**Comment by mbertrand** [comment]
Could be mac-specific, for some reason the width of the text input on Chrome (`div class="search-textbox"`) is significantly less than in FF (~311px vs 368px).

**Comment by mbertrand** [comment]
The problem does seem mac-specific, I opened the page in Chrome on an Ubuntu VM and it looks fine.

I can fix the problem on Mac by adding this to the `.search-textbox` style:

```css
  min-width: 330px;

  @include breakpoint(mobile) {
    min-width: unset;
  }
```

However it will still be truncated in mobile view:

Screen Shot 2019-03-22 at 12 41 55 PM

**Comment by aliceriot** [comment]
cool, I'm alright it being squished on mobile for now if you think it's ok, the placeholder text is long enough that it's pretty much always going to be squished on mobile  :/

**Comment by aliceriot** [comment]
(also I added those styles to `.search-textbox`)

**Comment by aliceriot** [comment]
(also I added those styles to `.search-textbox`)

**Pull request merged**
