### PR TITLE
changes to course page top bar

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

part of #1997

#### What's this PR do?

this changes the label in the couse-page-specific top bar to be in-line with the new designs. I also did a slight refactor in how we figure out when to show the course top bar vs the top bar for the rest of the site.

#### How should this be manually tested?

go to the homepage, things should look normal. then go to `/courses`, you should see something like the screenshots below. make sure it looks ok on mobile and so on.

#### Screenshots (if appropriate)

tobar
topbarmob

### CODE REVIEW

**Comment by Ferdi** [comment]
the MIT Open part the logo seems small. How does it  compare to the equivalent on the home page ? /cc @abdulkdawson

**Comment by aliceriot** [comment]
it's the same styling as on the home page, 14px

**Comment by abdulkdawson** [comment]
@aliceriot lets make it 16px. I think it would look better if we increased the font size a little.

**Comment by aliceriot** [comment]
here's how it looks with the bigger font:

coursesbiggerfontfff
coursesbiggerfont

**Comment by abdulkdawson** [comment]
@aliceriot I think it looks good.

**Comment by aliceriot** [comment]
@abdulkdawson what do you think about ^^ that?

**Comment by abdulkdawson** [comment]
@aliceriot the MIT Open should be center aligned with Learning.

**Comment by aliceriot** [comment]
I think the text is centered correctly, but the issue is that the vertical bar doesn't center-align:

alignedmaybe

in any case, the parent el for these things has `display: flex; align-items: center;` on it

**Comment by abdulkdawson** [comment]
@aliceriot if the vertical bar can not be centered then it is fine for now.

**Comment by aliceriot** [comment]
how's this?

betteraligned

**Comment by aliceriot** [comment]
@rhysyngsun updated the PR to fix that alignment issue

**Pull request merged**
