### PR TITLE
Add post editing

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

#231 

#### What's this PR do?

This adds UI for editing discussions posts (text posts). If the user is viewing the detail page for their own post there should be a an 'edit' button that opens a text box for editing the post.

#### How should this be manually tested?

You should be able to edit your own post, and you shouldn't be able to edit others! The edit button shouldn't show up on a url post.

### CODE REVIEW

**Comment by noisecapella** [comment]
I think according to the design the edit button should be lowercase

**Comment by noisecapella** [comment]
Also it looks like the voting and edit buttons are not visible when the edit box is open

**Comment by noisecapella** [comment]
I can edit text successfully but I see this warning in the console:
screenshot from 2017-11-27 12-32-12

**Comment by aliceriot** [comment]
comments should be addressed! I added a check to hide the button row if the post is currently being edited, and I fixed the `setState` issue as well.

**Pull request merged**
