### PR TITLE
Allow anonymous users to view the profile page and related posts and comments

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
https://trello.com/c/1KnhFWrP/64-anonymous-access-to-user-profiles

#### What's this PR do?
Allows anonymous access to the profile API and the related posts and comments API for profiles

#### How should this be manually tested?
As a logged out user view a profile page. You should not be redirected to a login page.

### CODE REVIEW

**Comment by aliceriot** [comment]
trying to view the profile page I get this error:

Screenshot from 2020-03-11 15-15-45

**Comment by aliceriot** [comment]
(in an incognito tab)

**Comment by noisecapella** [comment]
Do you see a different error when viewing the profile page while logged in?

**Comment by aliceriot** [comment]
I don't have any errors when I'm logged in, but my env env might be in a weird state because I just set it up

**Comment by aliceriot** [comment]
ok! I finally ironed out all the issues with my reddit setup and can confirm this works as advertised!

**Pull request merged**
