### PR TITLE
Default image for courses/bootcamps

### LINKED ISSUE #2141: Display a default course image if a course doesn't have one of its own
### Steps to Reproduce

Search courses for 'The Human Brain'.  

### Expected Behavior

There should be a default image shown if the imported course doesn't have one of its own.

### Actual Behavior

One of the results will have a broken image link.

### Screenshot or Screencast

Screen Shot 2019-08-07 at 9 37 05 AM

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review

#### What are the relevant tickets?
Closes #2141 

#### What's this PR do?
Displays a default image for courses & programs that don't have one of their own.

#### How should this be manually tested?
- Import edx data if you haven't done so (`docker-compose run web python manage.py backpopulate_edx_data`)
- Go to `/courses/search`, and search for "Harry's Lessons on Life"
- The search result card for that course should (try to) display the default course image via embedly - check the URL, it should be `https://i.embed.ly/1/display/crop/?key=<key>&url=http%3A%2F%2Fod.odl.local%3A8063%2Fstatic%2Fimages%2Fdefault_resource_thumb.jpg&height=130&width=306&grow=true&errorurl=http://od.odl.local:8063/static/images/blank.png`
- If you want to verify that it will actually display, you can use [ngrok](https://ngrok.com/) so embedly can reach the URL.
- Click the card to bring up the course drawer, it should also try to display the default image.

#### Screenshots
Screen Shot 2019-09-16 at 9 55 14 AM

Screen Shot 2019-09-16 at 9 55 21 AM

### CODE REVIEW

**Comment by mbertrand** [comment]
@pdpinch @Ferdi @abdulkdawson screenshots are in the description.

**Comment by abdulkdawson** [comment]
@mbertrand I'm going to update the image so that the logo on the list view is seen in full and not cut off.

**Comment by mbertrand** [comment]
screenshots updated with new image

**Comment by abdulkdawson** [comment]
@mbertrand much better. Thanks!

**Pull request merged**
