### PR TITLE
Facets for price and offered by

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #2212 

#### What's this PR do?
Adds facets for 'Offered By' and "Prices'

#### How should this be manually tested?
Go to `/courses/search/` and try out the new facets.

Note: the default behavior on search results is to show the lowest available price, which is often $0.  So even if you select only 'Paid' for the cost facet, lots of results will still display 'Free'.  

#### Screenshots (if appropriate)
Screen Shot 2019-09-13 at 12 21 35 PM

Screen Shot 2019-09-13 at 12 20 01 PM

### CODE REVIEW

**Comment by mbertrand** [comment]
@Ferdi @pdpinch @abdulkdawson screenshots attached

**Comment by mbertrand** [comment]
@noisecapella Nathan noticed that the ES mapping was off (should be "prices" instead of "price") and fixing that required some modifications to the query code to keep the cost facet working.  Just committed that change.

**Comment by noisecapella** [comment]
Just verified that it works. I'm fine to merge, but the search will start off broken before the `recreate_index` is run. Are we ok with having the course search be broken while the recreate_index is run? I'm also not sure how long that takes nowadays. @rhysyngsun

**Comment by rhysyngsun** [comment]
@noisecapella search still isn't released on production so the downtime is fine

**Pull request merged**
