### PR TITLE
Handle ALREADY_MODERATOR error

### LINKED ISSUE #290: Make moderator API idempotent
@rhysyngsun got an error which I was unable to reproduce: https://github.com/mitodl/micromasters/pull/3616#issuecomment-335538028

but this is now showing up on sentry: https://sentry.io/mit-office-of-digital-learning/discussions/issues/364467281/

Maybe there is a race condition between checking the moderator list and adding the new moderator?

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #290 

#### What's this PR do?
Fixes a race condition where the moderator was getting added twice in rapid succession and there was a difference in state between the if expression and the code to add the moderator. This changes it so that if reddit says the user already is a moderator the API returns a success.

#### How should this be manually tested?
Not sure if there's an easy way to test this except pushing it to CI and looking for sentry errors

### CODE REVIEW

**Comment by noisecapella** [comment]
@rhysyngsun Should be ready for review now

**Comment by rhysyngsun** [comment]
Code looks good.

**Comment by rhysyngsun** [comment]
@noisecapella I hit this error now:
```
web_1     | [2017-10-31 17:41:27] ERROR 23 [django.request] exception.py:124 - [6dd3fa8aad66] - Internal Server Error: /api/v0/channels/bobnew/moderators/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1     |     response = self._get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1     |     return view_func(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1     |     return self.dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 477, in dispatch
web_1     |     response = self.handle_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 437, in handle_exception
web_1     |     self.raise_uncaught_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 474, in dispatch
web_1     |     response = handler(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 243, in post
web_1     |     return self.create(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
web_1     |     self.perform_create(serializer)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
web_1     |     serializer.save()
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
web_1     |     self.instance = self.create(validated_data)
web_1     |   File "./channels/serializers.py", line 412, in create
web_1     |     return api.add_moderator(validated_data['moderator_name'], channel_name)
web_1     |   File "./channels/api.py", line 569, in add_moderator
web_1     |     Api(user).accept_invite(channel_name)
web_1     |   File "./channels/api.py", line 582, in accept_invite
web_1     |     self.get_channel(channel_name).mod.accept_invite()
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/models/reddit/subreddit.py", line 867, in accept_invite
web_1     |     self.subreddit._reddit.post(url)
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 411, in post
web_1     |     return self._objector.objectify(data)
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/objector.py", line 122, in objectify
web_1     |     raise APIException(*errors[0])
web_1     | praw.exceptions.APIException: NO_INVITE_FOUND: 'there is no pending invite for that subreddit'
```

**Comment by noisecapella** [comment]
@rhysyngsun I have a simple script to add, add again and remove the same contributor from a channel but I'm unable to reproduce that locally. Should we just merge this PR anyway and keep a look out for future occurrences?

**Comment by rhysyngsun** [comment]
@noisecapella I'm ok merging this as-is

**Pull request merged**
