### PR TITLE
Enabled scrollbar-on-hover behavior for the drawer

### LINKED ISSUE #1170: Hide scrollbar for side navigation
The sidebar doesn't look right with a scrollbar. 

Many users have scrollbars turned off for all scrollable regions, but we'd like to hide the scrollbar even for users who haven't set them to be hidden (see YouTube.com for example)

### PR DESCRIPTION
**Pull request by gsidebo**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1170

#### What's this PR do?
Adds `react-scrollbar` as a dependency and uses that component to wrap the drawer (side nav). This renders a custom scrollbar to the side of the drawer when one is needed

#### How should this be manually tested?
In desktop view, hover over the drawer. If it has enough content, you should see a scrollbar appear. Also check different browser widths to make sure everything renders correctly. 

#### Screenshots (if appropriate)
ss 2018-09-21 at 16 08 40
ss 2018-09-21 at 16 08 48
ss 2018-09-21 at 16 39 07

### CODE REVIEW

**Comment by gsidebo** [comment]
@pdpinch Just want to flag this as something we will definitely want to x-browser test on RC (or right now on CI if possible)

**Comment by gsidebo** [comment]
@mbertrand Did you rebuild the `watch` container for this PR branch, or run `./webpack_dev_server.sh --install` in the container manually? That isn't at all what you should be seeing

**Comment by mbertrand** [comment]
I destroyed my watch container and cleared out my node_modules folder, then rebuilt. Repeated again, same result.  Manually ran `./webpack_dev_server.sh --install` as well.

Here's a screenshot of the drawer after clicking to make it visible in a narrow and short browser tab:

screen shot 2018-09-24 at 3 47 17 pm

As compared to discussions-rc:

screen shot 2018-09-24 at 3 47 06 pm

**Comment by gsidebo** [comment]
@mbertrand OK yeah, your updated screenshot looks correct. Your first screenshot did not look correct. That grey divider you mention [here](https://github.com/mitodl/open-discussions/pull/1247#pullrequestreview-158216720) should not exist, and it looks like it doesn't exist in your new screenshot. That new screenshot is the intended look and feel. Are you seeing any buggy behavior?

**Comment by gsidebo** [comment]
@pdpinch Would like to get your feedback on this too. Might make the most sense for me to just have you look at it running on my machine tomorrow

**Comment by mbertrand** [comment]
@gsidebo, it still exists in a wide browser tab, when the drawer displays by default.

**Comment by pdpinch** [comment]
I got the review build partially working and so far I'm seeing the last thing that [Matt noted](https://github.com/mitodl/open-discussions/pull/1247#issuecomment-424109314) and desktop widths. 

Otherwise, it seems to be behaving, but I haven't been able to put enough channels into the review app yet to force scrolling.

**Comment by mbertrand** [comment]
Tried it again this morning and now I don't see that vertical gray bar on either my local build or discussions-rc, yesterday I saw it on both (full height on rc, partial height on this branch).  Not sure if it's because I'm not using my external monitor today or if the 3rd watch build is the charm (though that wouldn't explain RC).

**Comment by pdpinch** [comment]
What's your OS setting for scrollbars? I have mine set to "always"

screen shot 2018-09-25 at 9 08 54 am

**Comment by mbertrand** [comment]
Thanks @pdpinch, this morning it was set to "Automatically", so I set it to "Always" and the gray bar came back.  Not sure how/why it changed between yesterday and today.  Since it's an OSX issue I'll approve the PR.

**Pull request merged**
