### PR TITLE
search styles

### PR DESCRIPTION
**Pull request by abeglova**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  
Screen Shot 2022-08-09 at 8 06 10 PM
Screen Shot 2022-08-09 at 8 06 32 PM
Screen Shot 2022-08-09 at 8 07 11 PM
Screen Shot 2022-08-09 at 8 07 04 PM
Screen Shot 2022-08-09 at 8 06 57 PM

- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
https://github.com/mitodl/open-discussions/issues/3595

#### What's this PR do?
This pr fixes the styling for infinite corridor search on both desktop and mobile

#### How should this be manually tested?
Go to /infinite/search. Verify that the desktop site looks like the design at https://projects.invisionapp.com/d/main#/console/22082155/468407665/preview
There isn't a mobile design, so just verify that the mobile site isn't obviously broken

### CODE REVIEW

**Comment by Ferdi** [comment]
183788330-3ae08c39-1f37-4e8f-a819-9142a582a805-png-2194×1486-

**Review by mbertrand — COMMENTED** [review]
Overall looks great.  One minor nitpick - the certificate icon for me looks maybe a little too big, and not vertically aligned with the text?  Not sure how important that is.

Screen Shot 2022-08-10 at 9 51 07 AM

Screen Shot 2022-08-10 at 9 50 19 AM

**Comment by abeglova** [comment]
@Ferdi @mbertrand I made some changes. Let me know what you think. Here is how it looks now:
Screen Shot 2022-08-11 at 8 56 40 AM
Screen Shot 2022-08-11 at 8 57 26 AM
Screen Shot 2022-08-11 at 8 57 17 AM
Screen Shot 2022-08-11 at 8 57 06 AM
Screen Shot 2022-08-11 at 8 56 52 AM

**Comment by abeglova** [comment]
The search bar position is lined up with the cards, which is different from the design but worked better on varying screen sizes since the page is based on a 12 part grid with 3 parts for the facet and 9 for the cards

**Comment by abeglova** [comment]
Screen Shot 2022-08-11 at 10 26 13 AM

**Review by mbertrand — APPROVED** [review]
The certificate icon still looks a bit too big and not middle aligned with text, but not sure if that really matters.  Code/functionality looks fine so 👍

**Pull request merged**
