### PR TITLE
Moira integration

### LINKED ISSUE #2621: Integrate open with moira lists
Enable creation of private channels with membership based on moira lists.

Create a private channel, set membership_is_managed = True, and write a backend api/celery task to add users if they are on a moira list. This involves additional work to get moira list data into open. Could also be a restricted channel if we want that behavior too.

### LINKED ISSUE #2634: Moira integration
https://github.com/mitodl/open-discussions/issues/2621

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested
- [x] Settings
  - [x] New settings are documented and present in `app.json`
  - [x] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Closes #2621
Closes #2634

#### What's this PR do?
- Adds a MoiraList model
- Adds functions to retrieve a user's moira lists and a moira list's users
- Modifies ChannelMembershipConfig to support moira lists
- Adds functions/tasks to update channel memberships based on moira lists

#### How should this be manually tested?
- Set the following in your `.env` file:
  ```
  FEATURE_MOIRA=True
  MIT_WS_CERTIFICATE=<same as OVS-CI>
  MIT_WS_PRIVATE_KEY=<same as OVS-CI>
  ```
- Create a new channel in the django shell:
  ```
  from channels.api import get_admin_api
  api = get_admin_api()
  api.create_channel("ml1", title="managed moira channel 1", channel_type="private", 
  "membership_is_managed=True)
  ```

- In django admin, create a new ChannelMembershipConfig with query `{"moira_lists": ["<name_of_a_real_moira_list>"]}` and apply it to the new channel above.  An example real list is 'odl-engineering' which you should be a member of.

Screen Shot 2020-03-17 at 3 27 33 PM

- Log in as a user who belongs on the moira list used above.  A celery task should be kicked off, and after completion, if you reload the page, your new channel should show up in the left side bar.

### CODE REVIEW

**Comment by rhysyngsun** [comment]
Got this error trying to create a channel membership config:

```
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1      |     response = get_response(request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1      |     response = self.process_exception_by_middleware(e, request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
web_1      |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1      |     response = view_func(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1      |     response = view_func(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
web_1      |     return view(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
web_1      |     return self.changeform_view(request, None, form_url, extra_context)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1      |     return bound_method(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1      |     response = view_func(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
web_1      |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1572, in _changeform_view
web_1      |     self.save_model(request, new_object, form, not add)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
web_1      |     obj.save()
web_1      |   File "./channels/models.py", line 371, in save
web_1      |     for channel_id in self.channels.values_list("id", flat=True)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 527, in __get__
web_1      |     return self.related_manager_cls(instance)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 840, in __init__
web_1      |     (instance, self.pk_field_names[self.source_field_name]))
web_1      | ValueError: "<ChannelMembershipConfig: ODL Engineering>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

**Comment by mbertrand** [comment]
@rhysyngsun I think the new signal might have done away with the above error.

**Comment by mbertrand** [comment]
Noticed one more issue with non-kerberos moira list members that I'm going to fix

**Comment by mbertrand** [comment]
@rhysyngsun all set

**Pull request merged**
