### PR TITLE
Updated login tooltip prompt for anon users

### LINKED ISSUE #1222: fixup signup prompt for anonymous users
See [InVision](https://invis.io/9EN908ZQPAX) and [Zeplin](https://zpl.io/2ZzODOd)

### acceptance criteria:
- [ ] `Log In` text isn't displaying on login button
- [ ] Change "Become a Member" button to "Sign Up" to be consistent with other sign up UX
- [ ] Change prompt text to match Zeplin

### PR DESCRIPTION
**Pull request by gsidebo**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1222 

#### What's this PR do?
Changes the contents and styling of the login tooltip/popup for anonymous users ([example design in Zeplin](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5baa6eca6d1346b3722eae78))

#### How should this be manually tested?
Go to a post page as an anonymous user. 

#### Any background context you want to provide?
The issue wasn't very clear about which popups should be updated, so I only updated the popups for the cases where users focus on the post reply textarea and where they click the 'Reply' link under a comment. I left the contents for all other popups untouched

#### Screenshots (if appropriate)
ss 2018-10-02 at 16 04 18
ss 2018-10-02 at 16 04 05
(unchanged)
ss 2018-10-02 at 16 04 24

### CODE REVIEW

**Comment by gsidebo** [comment]
@pdpinch Let me know if you want those other popups (vote, follow, etc) updated as well

**Comment by pdpinch** [comment]
Why is the last one unchanged?

**Comment by gsidebo** [comment]
@pdpinch Updated

ss 2018-10-03 at 15 50 17

**Comment by gsidebo** [comment]
@noisecapella Sorry, can you re-review? I just made a bunch of updates

**Comment by gsidebo** [comment]
(...after I fix the build, of course)

**Comment by noisecapella** [comment]
Tried it out again, everything looks good :+1:

**Pull request merged**
