### PR TITLE
Added ES comment document indexing

### LINKED ISSUE #606: When a comment is made, add it to the search index

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?
Closes #606

#### What's this PR do?
Adds logic to create/update comment documents in Elasticsearch

#### How should this be manually tested?
- Set `FEATURE_INDEX_UPDATES=True` in your `.env`
- Create/update comments and check to see if those changes are reflected in the ES index
- Set a post to removed, then check to see that all comments associated with that post are also set to removed
- Delete a comment and check to see that the parent post's `num_comments` is decremented

#### Where should the reviewer start?
Probably `search/task_helpers.py`

#### Any background context you want to provide?
There are comments that say as much, but we are going ahead with an approach where we will log information about version conflicts in document updates and let the app continue to function as normal.

### CODE REVIEW

**Comment by gsidebo** [comment]
@mbertrand When you say 'delete a post', you mean 'remove', right? If so, comment count does not need to be updated, and the comments should be set to `removed=True`, not `deleted=True`. If you are actually deleting a post as opposed to removing it, I'm not actually sure how you can do that

**Comment by mbertrand** [comment]
@gsidebo I have links for both `delete` and `remove` on posts and comments,  maybe because I'm currently logged in as a superuser?

screen shot 2018-06-07 at 3 26 00 pm


screen shot 2018-06-07 at 3 27 53 pm

**Comment by gsidebo** [comment]
Huh, never even noticed that before. There isn't a channel API method for that. I guess I'll have to add one. I'll also add a task for updating child comments to set them to deleted

**Comment by gsidebo** [comment]
Great catch, by the wy

**Comment by gsidebo** [comment]
@mbertrand Ready for review again. I added indexing handlers for deleting a post (and updating all child comments), and changed up the approach to updating comments after a post is removed

**Comment by mbertrand** [comment]
@gsidebo getting an error on this branch:

```log
celery_1   | [2018-06-08 19:41:24,440: ERROR/PoolWorker-4] Task search.tasks.create_document[c43caafb-bbf5-4b06-8215-53f6e4008e84] raised unexpected: RequestError(400, 'mapper_parsing_exception', {'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.'}], 'type': 'mapper_parsing_exception', 'reason': 'Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.'}, 'status': 400})
celery_1   | Traceback (most recent call last):
celery_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
celery_1   |     R = retval = fun(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
celery_1   |     return self.run(*args, **kwargs)
celery_1   |   File "/src/search/tasks.py", line 54, in create_document
celery_1   |     return api.create_document(doc_id, data)
celery_1   |   File "/src/search/indexing_api.py", line 103, in create_document
celery_1   |     id=doc_id,
celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
celery_1   |     return func(*args, params=params, **kwargs)
celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 279, in create
celery_1   |     id, '_create'), params=params, body=body)
celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 314, in perform_request
celery_1   |     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
celery_1   |     self._raise_error(response.status, raw_data)
celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
celery_1   |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
```

**Comment by mbertrand** [comment]
Actually that error happens on master too (when creating a new post)

**Comment by gsidebo** [comment]
yep. finicky different requirements for the various ES API methods. looking into it now

**Pull request merged**
