### PR TITLE
Update ContentFile (Resource) ES doc structure

### LINKED ISSUE #3131: Update Elasticsearch doc content for resources
Resources in Elasticsearch should be updated to include the following information:

- [ ] Course run  slug from which a URL can be generated
- [ ] Course topics **
- [ ] A field specifying whether the resource is a pdf, HTML page, or video.***  
- [ ] Consistent links for files (always use the S3 links, but strip out the domain in the index so a CDN URL can be constructed instead).

** If topics are included in the resource docs, any change to the parent course's topics will require a reindex of its resources.

*** Currently, there is a `content_type` field ("file" or "page") and a `file_type` field (dozens of MIME type values like "video/mp4", "application/pdf").  Maybe `content_type` values can be modified for this. @ferdi @pdpinch what about other types?  Word docs, spreadsheets, images, etc?  There are many other resource types besides PDF's, pages, and videos.

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #3131 

#### What's this PR do?
- Adds `slug` field to `LearningResourceRun` model, adds `slug` to the ES LearningResourceRun docs.
- Uses the S3 url as the default url for all non-page resource files except external (non-OCW) links.
- Makes resource page url's relative.
- Populates/adds `topics`, `run_slug`, `short_url` and `run_title` to `ContentFile` (resource) docs in ElasticSearch.
- Adds 2 new `content_type` values, `pdf` and `video`, determined from the `file_type` (ie mime type)

#### How should this be manually tested?
- Run the new migration.  All OCW LearningResourceRuns should have a populated `slug` field afterward.
- Recreate the index.
- Run `backpopulate_ocw_files` management command.  
- Perform a search for OCW courses.  The raw search results should include a populated `slug` attribute for each course run.
- Run this search via curl/postman for resources, tweaking the content_type (try `pdf`, `page`, `video`, `file`).  Each resource should have the following populated fields: `topics`, `run_title`, `run_slug`, `content_type`, `file_type`.  The content_type should be `pdf` if the `file_type` ends with `pdf`, or `video` if the `file_type` starts with `video/`, or `page` if the `file_type` ends with `Section`, or `file` otherwise.

```
{  "size": 100,
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "object_type.keyword": "resourcefile"
                                }
                            }
                        ],
                        "must": [
                                {"term": {
                                    "content_type": "pdf"
                                }   }                         
                        ]
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "has_parent": {
                                    "parent_type": "resource",
                                    "query": {
                                        "bool": {
                                            "should": [
                                                {
                                                    "term": {
                                                        "offered_by": "OCW"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

### CODE REVIEW

**Comment by mbertrand** [comment]
@pdpinch @Ferdi should we wait for feedback from OCW on what content_types they are interested in, or add them in later PR's as they trickle in?  This PR adds `pdf` and `video`, any other non-page resource will continue to have a content_type of `file`.

**Comment by pdpinch** [comment]
Sorry if this has been asked and answered already:

- What are you doing with "HTML" or "Section" content?
- is there a field that captures the mime-type or similar?

**Comment by mbertrand** [comment]
HTML/Section content:  `content_type` is `page`, file_type is one of `DownloadSection`, `CourseSection`, or a couple others - this PR doesn't change any of that.  This PR does add `short_url` which should have a non-null value for pages but not other files.

`file_type` contains the mime-type for non-page resources, this is used to determine if the content_type should be `pdf` or `video`.  But there are dozens of other mime types, for word docs, spreadsheets, code files, text files, etc.

**Review by abeglova — APPROVED** [review]
👍

**Pull request merged**
