### PR TITLE
Changed article thumbnail rendering to serve from embedly

### LINKED ISSUE #1745: Figure out post summary styling needs and user-uploaded thumbnail dimensions
#1733 (PR #1741) made some styling updates to post summary cards. Among the desired changes: make the thumbnail occupy more space so the cards look less sparse. This was doable with link thumbnails since we can request exact dimensions from embedly, so we increased the width and height in our requests. User-submitted article cover images, on the other hand, are uploaded in our own back-end and the thumbnails are restricted to exact dimensions (201px wide, 103px tall). As a result, we have no good way of increasing the vertical space that these thumbnails occupy.

Possible solutions:
- Batch update script to generate new thumbnails with increased dimensions
- Upload all existing thumbnails to embedly, and have them serve our thumbnails instead

EDIT (02/05/2019):
- We will be using embedly to serve the article thumbnails from S3
- As part of this issue, we also want to configure development environments to upload to S3 so we can see these images when we run the app locally

### PR DESCRIPTION
**Pull request by gsidebo**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots 
  - [x] Mobile width screenshots 
  - [x] tag @ferdi or @pdpinch for review  
- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1745

#### What's this PR do?
- Uses embedly to serve thumbnails for our article cover images (like we've already been doing for link post thumbnails)
- Gets rid of old logic to generate article thumbnail on the fly, and get rid of the DB column that stored the image (the main cover image src is used instead to generate the thumbnail via embedly)

#### How should this be manually tested?
- Add `OPEN_DISCUSSIONS_USE_S3=True` in your `.env` file
- Also `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_STORAGE_BUCKET_NAME` in your `.env`. You can get the appropriate values from Heroku CI
- Create an article post and upload a cover image. The thumbnail for that post on a post listing should look correct at all screen widths.
- Create a link post. Same deal as above for the link preview thumbnail.

#### Any background context you want to provide?
- Old uploaded images for articles will have broken thumbnail images since they were previously saved to the local FS. This won't be a problem on prod since article images have always been uploaded to S3

#### Screenshots (if appropriate)
ss 2019-02-05 at 16 34 57
ss 2019-02-05 at 16 35 08
ss 2019-02-06 at 16 53 50

### CODE REVIEW

**Comment by gsidebo** [comment]
@pdpinch screenshot review please! ^^^

**Comment by pdpinch** [comment]
LGTM. I appreciate the screenshot with code snippet!

It doesn't make a difference to me either way, but I thought @mitodl/devops had wanted to get a dev-only bucket instead of reusing the CI bucket?

**Comment by blarghmatey** [comment]
I'm agnostic as to whether we use a dev or CI bucket as long as it works for the developers needs.

**Comment by gsidebo** [comment]
Great catch. Meant to update the readme & forgot

**Pull request merged**
