### PR TITLE
Adds in Offered By

### PR DESCRIPTION
**Pull request by kyfantaz**
_This PR is to get a jumpstart on code review for code that's waiting for #2056 to be merged into master_ 
Once this code and #2056 are approved, this PR can be remade against `master` for actual merging.

#### What are the relevant tickets?
TBD

#### What's this PR do?
We want to label LearningResources with "Offered By"
This adds a new optional field `offered_by` to models, a migration to backfill the new field, and includes it in the indexing code of #2056.

#### How should this be manually tested?
Migrate the migration and see if the new field is returned in the backend courses API return.

### CODE REVIEW

**Comment by kyfantaz** [comment]
@mbertrand Addressed in 801dd22. However, is it OK to label all incoming courses from edx as offered by `MITx` (will there be any courses we would want to label as xPro or MicroMasters that come in from the edx API sync)?

**Comment by mbertrand** [comment]
@kyfantaz [course_catalog.task_helpers.tag_edx_course_program](https://github.com/mitodl/open-discussions/blob/ece01da44272c1200b29e7bb30895ec674cd1914/course_catalog/task_helpers.py#L498-L534) should be modified to assign the correct value for `offered_by`.

**Comment by kyfantaz** [comment]
@mbertrand Addressed in e7aa491. However, I believe [Ferdi mentioned here] (https://mitodl.slack.com/archives/GHYAV2GF3/p1561149469111600) that he believes that code should be slated for removal in the near future in favor of a replacement.

**Comment by kyfantaz** [comment]
Thanks for the review @mbertrand . I'm remaking this PR against master for actual merging.

**Pull request closed without merging**
