### PR TITLE
tweaks to channel appearance form page

### LINKED ISSUE #1203: Moderator UI doesn't match the design
The channel appearance UI doesn't quite match the [design in Invision](https://projects.invisionapp.com/d/main#/console/14986667/311617720/preview) (The 'Upload banner' link is a button with different text in the design)

ss 2018-09-17 at 17 55 35

_Screenshot taken on the #1153 PR branch_

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #1203 

#### What's this PR do?

Some tweaks to the channel settings page to bring it more in line with the mocks.

#### How should this be manually tested?

Check out the channel settings page, referring to the changes requested on the issue. make sure it makes sense!

### CODE REVIEW

**Comment by gsidebo** [comment]
This is what I'm seeing:

ss 2018-09-27 at 14 31 54

This is the design I'm comparing it to: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b60e696d25d8c4565e10c75

That design has a different avatar upload interface among other things. Is that not the right design?

**Comment by aliceriot** [comment]
not sure, I was working from this one: https://projects.invisionapp.com/d/main#/console/14986667/311617720/preview

@pdpinch @loemerdotcom which one should we be using?

**Comment by gsidebo** [comment]
In that design you linked, the pencil icon looks different from my screenshot

**Comment by aliceriot** [comment]
yea I can change that

**Comment by aliceriot** [comment]
I'm still working off that b/c I haven't heard otherwise, and that one was linked in the issue but :woman_shrugging: 

with the icon the existing implementation has a 'plus' icon if no picture has been added and a pencil otherwise. I can switch it to just use the pencil.

**Comment by aliceriot** [comment]
@pdpinch we currently use the same component for uploading the channel avatar and the profile image. we have a thing which, as described above, shows a plus sign if the user hasn't yet added an image, and changes to a pencil icon if they already have one. I just want to confirm whether we want to keep that behavior or not, I see the pencil icon used in the mocks when no channel avatar has been added, but I don't see a mock of the profile image uploader before an image has been added, so I just wanted to confirm before I changed it to always use the pencil icon.

**Comment by pdpinch** [comment]
Sorry for the confusion. What I can say confidently is that we should stick to the same component in both. 

Regarding the + versus the pencil, I think we should stick with what we have for the moment. If/when Lucas weighs in with a different approach, we can do an update. (I'd be nice to center the plus everywhere, but I can live with that for a bit).

**Comment by aliceriot** [comment]
@pdpinch @gsidebo ok I fixed the display of the little 'edit' icon on the image, and I left the 'pencil' / 'plus' sign feature in.

**Pull request merged**
