### PR TITLE
Fix OLL logo image

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review

#### What are the relevant tickets?
Fixes https://trello.com/c/YkFGXP6a/237-bug-wrong-logo-for-oll-course

#### What's this PR do?
Replaces the MIT Open image being used as the OLL logo with a correct version, resized to match the old image's size.

#### How should this be manually tested?
Go to `/learn/search` and filter on "Open Learning Library" under the "Offered By" facet. You should see an image similar to the one in the screenshot.

#### Screenshots
Screenshot from 2020-03-27 15-49-53

### CODE REVIEW

**Comment by aliceriot** [comment]
I wonder if we should make some adjustment so it doesn't get all squished like this?

Screenshot from 2020-03-30 11-15-26

compare with how it is on master:

Screenshot from 2020-03-30 11-16-27

**Comment by noisecapella** [comment]
@aliceriot Yes I was wondering about that. I resized the image to match the previous one but I can resize to the MIT Open instead. Any thoughts @pdpinch?

**Comment by pdpinch** [comment]
I think it's OK to make it smaller so it can fit reliably. 

We are planning to redesign the drawer to give it more space, so it's not worth futzing with this too much.

**Comment by noisecapella** [comment]
@aliceriot I added some padding on the top and bottom so it matches the previous image better
Screenshot from 2020-03-31 15-05-47

**Comment by noisecapella** [comment]
@aliceriot Any other comments?

**Comment by aliceriot** [comment]
sorry, haven't had a chance to take a look yet

**Pull request merged**
